language: ruby

rvm:
  - '2.5.0'

addons:
  postgresql: "9.6"

env:
  IMAGE_NAME=hermesdt/insbef
  IMAGE_TAG=$IMAGE_NAME:$TRAVIS_TAG
  IMAGE_LATEST=$IMAGE_NAME:latest

install:
  bundle install

stages:
  - test
  - name: create_git_tag
    if: branch = master
  - name: docker_build
    if: tag =~ ^v
  # - deploy

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: rails spec
    - stage: create_git_tag
      before_script:
        - psql -c 'create database insbef_test;' -U postgres
        - rake db:migrate
      script:
        - git config --global credential.helper store
        - echo $GIT_CI_CREDENTIALS > $HOME/.git-credentials
        - export NEW_TAG=$(sh bin/semver.sh)
        - git tag $NEW_TAG
        - git push origin $NEW_TAG
    - stage: docker_build
      script:
        - echo "Login in docker $DOCKER_USERNAME"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "Building images $IMAGE_TAG, $IMAGE_LATEST"
        - docker build . -t $IMAGE_TAG -t $IMAGE_LATEST
        - echo "Pushing image $IMAGE_TAG"
        - docker push $IMAGE_TAG
        - echo "Pushing image $IMAGE_LATEST"
        - docker push $IMAGE_LATEST
